### ISSUE TITLE
Allow specification of RA/DEC column in build-index

### ISSUE THREAD

**Issue by keflavich** [astrometry/usermanual#2]
Feature request.  Is there any way I can submit pull requests?  I don't see the source code here...

This is all that needs to be done:

in `build-index-main.c`, add:

```
        case 'A': # 'A' instead of 'R' because both 'R' and 'r' are used
            p->racol = optarg;
            break;
        case 'D':
            p->deccol = optarg;
            break;

```

and change:
`const char* OPTIONS = "hvi:o:N:l:u:S:fU:H:s:m:n:r:d:p:R:L:EI:MTj:1:P:B:A:D:";`

**Comment by dstndstn** [comment]
Sorry for taking so long to handle this!

The source code still lives in SVN at   http://astrometry.net/svn/trunk/src/astrometry/
so it's not currently possible to send pull requests via github.  I am thinking about putting a fork on github though...

Thanks for the patch -- I have applied it, and it will appear in the next release.

**Comment by keflavich** [comment]
I think the svn->git transition isn't too bad; I've done it with mercurial & automated tools and had little trouble in the past.  Just saying, you might get more pull requests if you have code on github....   ...but I could also understand not wanting that.
