### ISSUE TITLE
No "Orientation" in API?

### ISSUE THREAD

**Issue by kevinalle** [astrometry/usermanual#5]
Hi,
I am using the nova API and I am getting good RA, DEC and RADIUS results from the job calibration (/api/jobs/JOBID/calibration).
Now, in the dashboard's calibration I also see "orientation" and "pixel scale". Is it possible to get this data from the API?
Thank you!!

**Comment by dstndstn** [comment]
Thanks for filing this issue!  I just added those result fields to our development site:
http://supernova.astrometry.net

Please feel free to test/use that.

And I will update "nova" as soon as I finish running a backup cycle.

**Comment by kevinalle** [comment]
Dustin Thanks a LOT! that is relly helpful :)
I also found a workaround:
I download the wcs.fits header (this is not actually the API but is easily accessible through http://nova.astrometry.net/wcs_file/JOBID) and from there I get CRPIX1, CRPIX2, CRVAL1, CRVAL2,and the CD matrix, which is _exactly_ what I need.
Thanks again!
