### ISSUE TITLE
Text files (list of X, Y) no longer supported?

### ISSUE THREAD

**Issue by kevinalle** [astrometry/usermanual#6]
Hi,
I've been using the API with lists of X, Y positions. It worked some days ago and recently stopped working.
I also tried uploading via the webpage a text file with 2 columns of digits separated by whitespace, listing the X,Y positions of sources (as described in http://nova.astrometry.net/upload), and fails with:

```
File "process_submissions.py", line 488, in get_or_create_image
    raise Exception('This file\'s type is not supported.')
Exception: This file's type is not supported.
```

How can I use the API with text files?
Thanks!!

**Comment by dstndstn** [comment]
Thanks for the report!  Could you please attach an example file here?

**Comment by dstndstn** [comment]
example here
https://gist.github.com/dstndstn/5161463

**Comment by dstndstn** [comment]
I put in some fixes for handling xylists via the web interface.  Haven't checked the API yet.  Could you please test out  http://staging.astrometry.net  ?  Thanks!

**Comment by kevinalle** [comment]
Indeed, the API now works with xylists in staging.
Do you think I can switch to nova soon?
Thanks Dustin!!

**Comment by dstndstn** [comment]
I just updated nova.

**Comment by kevinalle** [comment]
works wonderfully, thanks
