### ISSUE TITLE
libnetpbm not detected

### ISSUE THREAD

**Issue by letmaik** [astrometry/usermanual#8]
In the readme and forum it says that netpbm cannot be detected easily. Why?

I use Ubuntu, installed libnetpbm10-dev netpbm via package manager as described in the readme and can do:

```
$ whereis libnetpbm
libnetpbm: /usr/lib/libnetpbm.so /usr/lib/libnetpbm.a
$ dpkg-query -L libnetpbm10
...
/usr/lib/libnetpbm.so.10.0
...
/usr/lib/libnetpbm.so.10
```

So why isn't this information used in configure/make?

At the moment, I have exactly that problem and need to fiddle around with NETPBM_LIB and NETPBM_INC, which is unnecessary I think.

**Comment by dstndstn** [comment]
Because it has to run on Mac, Redhat, Suse, Slackware, etc.  dpkg-query is debian-specific, and whereis only searches "standard" places.  On my mac:

```
> whereis libnetpbm.a
> whereis libnetpbm.so
> whereis libnetpbm.dylib
> whereis libnetpbm
> dpkg-query
-bash: dpkg-query: command not found
```

**Comment by dstndstn** [comment]
Besides, if you have it installed there, the defaults should work just fine.

**Comment by letmaik** [comment]
I got it running by using this in makefile.netpbm:

```
NETPBM_INC=-I/usr/include
NETPBM_LIB=-L/usr/lib -lnetpbm
```

**Comment by letmaik** [comment]
It didn't work with the defaults, but don't ask me why.

**Comment by dstndstn** [comment]
Actually, I really do want to ask you why!  Definitely /usr/include is in the default search path, and definitely /usr/lib is in the default library search path.

Could you please try with the defaults and send the error message you get?

thanks!

**Comment by letmaik** [comment]
```
---- Error messages in the next few commands are not necessarily bugs ----
     (we're checking how things works on your computer)
rm -f os-features-makefile.log
( \
     echo "# This file is generated by util/Makefile."; \
     ((gcc -o os-features-test-netpbm-make \
        -g -Wall -ffinite-math-only -fno-signaling-nans -pthread -march=native -O3 -fomit-frame-pointer -DNDEBUG -fPIC -Winline -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12    -I/usr/include/libpng12   -I../gsl-an   -I../qfits-an/include -I../libkd -I. -DTEST_NETPBM_MAKE  os-features-test.c  -g -Wall -ffinite-math-only -fno-signaling-nans -pthread -march=native -O3 -fomit-frame-pointer -DNDEBUG -fPIC -Winline  >> os-features-makefile.log && \
       ./os-features-test-netpbm-make >> os-features-makefile.log && \
       echo "HAVE_NETPBM := yes") \
    || (echo "# Astrometry.net didn't find netpbm; not setting HAVE_NETPBM."; \
        echo "# See os-features-makefile.log for details."; \
        echo "# To re-run this test, do 'make reconfig; make makefile.os-features' (in the 'util' directory)"; \
        echo "# Or to do it yourself, just uncomment this line:"; \
        echo "# HAVE_NETPBM := yes")) \
    ; \
    echo) > makefile.os-features.tmp
/tmp/ccdx1Jpu.o: In function `main':
/home/ubuntu/astrometry.net-21979/util/os-features-test.c:91: undefined reference to `pm_init'
collect2: ld returned 1 exit status
``
```

**Comment by letmaik** [comment]
I just tried it with the latest version (0.42) and it seems to work there. So, seems you fixed something from 21979. By the way, where are the changelogs?

Edit: The reason I didn't use the newest version was because I actually thought there were no newer ones as I used the latest snapshot (which strangely is older than the newest version)

**Comment by dstndstn** [comment]
I'm afraid there are no changelogs...

Yeah, I've been working toward a new release for use by LSST, so have been making releases rather than snapshots recently.

Since this works for you in the latest release, I'm going to close this issue.  Reopen if you disagree.

Thanks!

**Comment by fehlfarbe** [comment]
I tried to install astrometry.net 0.50 on my Linux Mint 17 (64 bit) system with similar problems. Adding the include paths at makefile.netpbm didn't help. Make couldn't find /usr/include/netpbm/pam.h and /usr/include/netpbm/ppm.h because the headers where at /usr/include not at /usr/include/netpbm

I just added a directory and symlinks to the headers:

> sudo mkdir /usr/include/netpbm
> sudo ln -s /usr/include/pam.h /usr/include/netpbm/pam.h
> sudo ln -s /usr/include/ppm.h /usr/include/netpbm/ppm.h

Now it's working :)
